id = "modu-syntax"
name = "Modu Syntax Highlighting"
version = "1.0.0"
schema_version = 1
authors = ["Cyteon <me@cyteon.dev>"]
description = "Syntax highlighting for modu files"
repository = "https://github.com/cyteon/modu"

[grammars.modu]
repository = "https://github.com/cyteon/tree-sitter-modu"
rev = "a320fb973d93ac5024ad0a9c608b92634603b4d3"
