id = "modu-lang"
name = "Modu Lang"
version = "0.0.1"
schema_version = 1
authors = ["Cyteon"]
description = "Syntax highlightning for the Modu Programming Language"
repository = "https://github.com/your-name/my-zed-extension"