id = "modu-syntax"
name = "Modu Syntax Highlighting"
version = "1.0.0"
schema_version = 1
authors = ["Cyteon <me@cyteon.dev>"]
description = "Syntax highlighting for modu files"
repository = "https://github.com/cyteon/modu"

[grammars.modu]
repository = "https://github.com/cyteon/tree-sitter-modu"
rev = "660f60ea6e506a7e939c725d0f63b3a3f4bebde5"
