name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        ls
        cd lang
        cargo test --verbose
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build for Linux
      run: |
        cd lang
        cargo build --release --verbose
    
    - name: Build for Windows
      run: |
        cd lang
        cargo build --release --verbose --target x86_64-pc-windows-gnu

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          lang/target/x86_64-pc-windows-gnu/release/modu.exe
          lang/target/release/modu
